### ISSUE TITLE
Html in Attribute values cause build errors in current CI builds

### ISSUE THREAD

**Issue by Suchiman** [aspnet/Blazor#773]
```cshtml
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="<div>Test!</div>" />
```
will cause
```
One or more errors occurred. (Unexpected node type Microsoft.AspNetCore.Blazor.Razor.HtmlElementIntermediateNode)
at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
at Microsoft.AspNetCore.Razor.Tools.GenerateCommand.GenerateCode(RazorProjectEngine engine, SourceItem[] inputs)
at Microsoft.AspNetCore.Razor.Tools.GenerateCommand.ExecuteCore(RazorConfiguration configuration, String projectDirectory, String tagHelperManifest, List`1 sources, List`1 outputs, List`1 relativePaths)
at Microsoft.AspNetCore.Razor.Tools.GenerateCommand.ExecuteCoreAsync()
at Microsoft.AspNetCore.Razor.Tools.CommandBase.<ExecuteAsync>d__10.MoveNext()
packages\microsoft.aspnetcore.blazor.build\0.4.0-preview1-10282\targets\RazorCompilation.targets(281,5): error : rzc generate exited with code 1. [WebApplication7\WebApplication7\WebApplication7.csproj]
```

**Comment by rynowak** [comment]
Thanks, I'll take a look at this.

**Comment by rynowak** [comment]
Thanks for the report, this should be fixed in the dev branch now.

**Comment by rynowak** [comment]
Scratch that. I closed the wrong one...

**Comment by rynowak** [comment]
Thanks for the report, this is fixed now in dev.

**Comment by Suchiman** [comment]
@rynowak i just tried and its not fixed, it also seems your test case is broken.
If you check those two lines: https://github.com/aspnet/Blazor/blob/73620cc0915824435d089621fbcf380a19484555/test/Microsoft.AspNetCore.Blazor.Build.Test/TestFiles/RuntimeCodeGenerationTest/Regression_773/TestComponent.codegen.cs#L23-L24
they start an `Element` instead of an `Component`.
With your changes, invalid C# gets generated:
```csharp
// <auto-generated/>
#pragma warning disable 1591
namespace WebApplication7.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Blazor;
    using Microsoft.AspNetCore.Blazor.Components;
    using System.Net.Http;
    using Microsoft.AspNetCore.Blazor.Layouts;
    using Microsoft.AspNetCore.Blazor.Routing;
    using WebApplication7;
    using WebApplication7.Shared;
    [Microsoft.AspNetCore.Blazor.Layouts.LayoutAttribute(typeof(MainLayout))]

    [Microsoft.AspNetCore.Blazor.Components.RouteAttribute("/")]
    public class Index : Microsoft.AspNetCore.Blazor.Components.BlazorComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
            builder.OpenElement(0, "h1");
            builder.AddContent(1, "Hello, world!");
            builder.CloseElement();
            builder.AddContent(2, "\n\nWelcome to your new app.\n\n");
            builder.OpenComponent<WebApplication7.Shared.SurveyPrompt>(3);
            builder.AddAttribute(4, "Title", );
            builder.CloseComponent();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
```

**Comment by rynowak** [comment]
OK thanks for updating. I'll get to the bottom of this.

**Comment by rynowak** [comment]
@Suchiman - thanks so much for your help on this. This should really be fixed now.
