### ISSUE TITLE
fetch request removes header information

### ISSUE THREAD

**Issue by abhishekgoenka** [aspnet/Blazor#929]
I am passing valid header to fetch api
![image](https://user-images.githubusercontent.com/14522198/40985765-6bf49e7e-6902-11e8-8c0a-5eafa8317501.png)

fetch api code(Http.ts)
![image](https://user-images.githubusercontent.com/14522198/40985815-8103ad46-6902-11e8-8a87-58d0741875c4.png)

But request removes my headers. 
![image](https://user-images.githubusercontent.com/14522198/40985885-9ab93652-6902-11e8-96c1-6cc7f0717041.png)

**Comment by Suchiman** [comment]
I would suspect https://github.com/aspnet/Blazor/pull/815#issuecomment-388322179 fixes this as a side effect, you could try a CI build to see if it does: https://github.com/aspnet/Blazor#using-ci-builds-of-blazor

**Comment by SteveSandersonMS** [comment]
Yes, this is fixed in 0.4.0. Thanks for reporting it, though!

**Comment by abhishekgoenka** [comment]
I took the latest code but still facing the same issue. The only change I have made is `requestInit.mode = 'no-cors';`

![image](https://user-images.githubusercontent.com/14522198/40990100-5e01d8e4-690d-11e8-9c27-c1da5d54098a.png)

**Comment by Suchiman** [comment]
@abhishekgoenka you can set mode = "no-cors" just by using
```csharp
var requestMessage = new HttpRequestMessage();
requestMessage.Properties.Add("BrowserHttpMessageHandler.FetchArgs", new { mode = "no-cors" });
```

But aside from that, i believe this isn't a bug, it's a feature.
https://developer.mozilla.org/en-US/docs/Web/API/Request/mode
> `no-cors` — Prevents the method from being anything other than HEAD, GET or POST, and the headers from being anything other than simple headers.
`Authorization` and `Content-Type: application/json` are both not simple header, so you're asking for it.
